# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_run
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_run)
  AquEngine_config = debug_run

else ifeq ($(config),debug_static-build)
  AquEngine_config = debug_static-build

else ifeq ($(config),debug_dynamic-build)
  AquEngine_config = debug_dynamic-build

else ifeq ($(config),release_run)
  AquEngine_config = release_run

else ifeq ($(config),release_static-build)
  AquEngine_config = release_static-build

else ifeq ($(config),release_dynamic-build)
  AquEngine_config = release_dynamic-build

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := AquEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AquEngine:
ifneq (,$(AquEngine_config))
	@echo "==== Building AquEngine ($(AquEngine_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(AquEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_run"
	@echo "  debug_static-build"
	@echo "  debug_dynamic-build"
	@echo "  release_run"
	@echo "  release_static-build"
	@echo "  release_dynamic-build"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AquEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"